[package]
name = "rust_combined"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure_detector = { path = "failure_detector", version = "0.1.0" }
inc = { path = "inc", version = "0.1.0" }
seastar = { path = "seastar", version = "0.1.0" }
wasmtime_bindings = { path = "wasmtime_bindings", version = "0.1.0" }
unit_tests = { path = "../test/rust/", version = "0.1.0", optional = true }

[lib]
crate-type = ["staticlib"]

[features]
tests = ["unit_tests"]
